spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

aws:
  s3:
    directory: ${AWS_S3_DIRECTORY:products}
    max-file-size: ${AWS_S3_MAX_FILE_SIZE:5242880}
