spring:
  config:
    import: aws-parameterstore:/used-market/prod/
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: true

aws:
  s3:
    max-file-size: ${AWS_S3_MAX_FILE_SIZE:5242880}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}
